CREATE DATABASE Clientes
USE Clientes
CREATE TABLE if not exists Clientes (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL,
    CIDADE VARCHAR(100) NOT NULL
    );

INSERT INTO Clientes (ID, NOME, IDADE, CIDADE)
VALUES (1037, "THIAGO KLAUBER", 32, "JABOATÃO DOS GUARARAPES")

SELECT * FROM Clientes